application: get-unseen
module: bakery
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: .*
  script: main.app